import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';
import { ButtonDefault } from '../components/ButtonDefault';
import { HeadingDefault } from '../components/HeadingDefault';
import { LayoutHome } from '../components/LayoutHome';
import { TextDefault } from '../components/TextDefault';
import styles from './styles.module.scss';
import { GridDefault } from '../components/GridDefault';

const ImgHome = '/images/desenho.svg';
const ImgSeta = '/images/seta-bacgound.svg';

const Home: NextPage = () => {
  return (
    <div className={styles.home_container}>
      <Head>
        <title>DSCATALOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutHome title={'Home'}>
        <GridDefault>
          <GridDefault size={2}>
            <GridDefault>
              <HeadingDefault target={'h3'}>
                Conheça o melhor catálogo de produtos
              </HeadingDefault>
              <TextDefault mb={10}>
                Ajudaremos você a encontrar os melhores produtos disponíveis no
                mercado.
              </TextDefault>
              <ButtonDefault
                icon
                src={ImgSeta}
                size={'medium'}
                title={'INICIE AGORA A SUA BUSCA'}
                onClick={() => console.log('Click')}
              >
                Button
              </ButtonDefault>
            </GridDefault>

            <Image
              src={ImgHome}
              alt={'Imagem buscando por um produto'}
              width={650}
              height={480}
            />
          </GridDefault>
        </GridDefault>
      </LayoutHome>
    </div>
  );
};

export default Home;
