import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';
import { Button } from '../components/Button';
import { Heading } from '../components/Heading';
import { LayoutHome } from '../components/LayoutHome';
import { Text } from '../components/Text';
import styles from './styles.module.scss';

const ImgHome = '/images/desenho.svg';
const ImgSeta = '/images/seta-bacgound.svg';

const Home: NextPage = () => {
  return (
    <div className={styles.home_container}>
      <Head>
        <title>DSCATALOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutHome title={'Home'}>
        <div className={'shadow box-shadow'}>
          <div className={'grid-2'}>
            <div className={''}>
              <Heading target={'h3'}>
                Conheça o melhor catálogo de produtos
              </Heading>
              <Text mb={10}>
                Ajudaremos você a encontrar os melhores produtos disponíveis no
                mercado.
              </Text>
              <Button
                icon
                src={ImgSeta}
                size={'medium'}
                title={'INICIE AGORA A SUA BUSCA'}
                onClick={() => console.log('Click')}
              >
                Button
              </Button>
            </div>
            <Image
              src={ImgHome}
              alt={'Imagem buscarndo por um produto'}
              width={650}
              height={480}
            />
          </div>
        </div>
      </LayoutHome>
    </div>
  );
};

export default Home;
